### PR TITLE
refactor logic into lib

### PR DESCRIPTION
**Pull request by majormoses**
added .rubocop.yml
updated rest-client

### CODE REVIEW

**Comment by majormoses** [comment]
@eheydrick im traveling this week for work so I wont have much time to do some more refactoring. There was one thing that caught my eye as potentially dangerous using `eval`. Can you think of a safer way to do whats needed here?

**Comment by eheydrick** [comment]
Thanks @majormoses. I will take a look at your changes this week. I'm not a fan of that eval either, will come up with something better.

**Comment by majormoses** [comment]
@eheydrick have a chance to take a look?

**Comment by eheydrick** [comment]
Hey @majormoses, apologies for the delay, I should have time to review on monday.

**Comment by eheydrick** [comment]
Need to add the lib to the gem. `s.files       = Dir.glob("{bin,lib}/**/*.rb")` will do it.

**Comment by eheydrick** [comment]
I tested this out and webhooks and sensu chat notifications aren't working. Looks like for chat it just needs `config` passed. 

```
Error generating template: undefined method `get_chef_fqdn' for #<AwsCleaner:0x00000002367a70>
Failed to run webhook ipa-node-deleterError generating template: undefined method `get_chef_fqdn' for #<AwsCleaner:0x00000002367a70>
Failed to run webhook ipa-node-deleter
```

```
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-cleaner-2.1.0/lib/aws_cleaner/aws_cleaner.rb:130:in `notify_chat': wrong number of arguments (1 for 2) (ArgumentError)
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-cleaner-2.1.0/lib/aws_cleaner/aws_cleaner.rb:85:in `remove_from_sensu'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-cleaner-2.1.0/bin/aws_cleaner.rb:94:in `block (2 levels) in <top (required)>'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-cleaner-2.1.0/bin/aws_cleaner.rb:57:in `each'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-cleaner-2.1.0/bin/aws_cleaner.rb:57:in `each_with_index'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-cleaner-2.1.0/bin/aws_cleaner.rb:57:in `block in <top (required)>'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-cleaner-2.1.0/bin/aws_cleaner.rb:47:in `loop'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-cleaner-2.1.0/bin/aws_cleaner.rb:47:in `<top (required)>'
        from /opt/chef/embedded/bin/aws_cleaner.rb:22:in `load'
        from /opt/chef/embedded/bin/aws_cleaner.rb:22:in `<main>'
```

**Comment by eheydrick** [comment]
Thoughts on splitting the modules out into separate files?

**Comment by majormoses** [comment]
@eheydrick Indeed thats a fantastic idea, I was going for minimal change at first and then splitting out further classes (not a single class with a bunch of modules but that might be easier) in other prs. I have some changes I am gonna push that might fix the issue you saw. I will try to test it out if not I will try to set up some test cases later today or tomorrow.

**Comment by eheydrick** [comment]
Otherwise, looks 👍. Thanks!

**Comment by majormoses** [comment]
@eheydrick here is what I see running it (I think that my keepalives are too low to see whats happening with sensu) can you confirm if this works for you:

```
$ ./bin/aws_cleaner.rb -c config.yml
Got 0 messages
<REMOVED_REPEATING_MESSAGE>
Got 1 messages
Looking at message number 0
Instance i-1d26d3c1 does not exist in Chef, deleting message
Got 0 messages
Looking at message number 0
Removed ip-10-55-141-179.us-west-2.compute.internal from Chef
Got 0 messages

```

My testing was really quite simple (moving the /etc/rc.0/ scripts for de-registering sensu and chef)

**Comment by eheydrick** [comment]
Removing from chef is working for me. 

```
Got 1 messages
Looking at message number 0
Error generating template: undefined method `get_chef_fqdn' for #<AwsCleaner:0x00000002367a70>
Failed to run webhook ipa-node-deleter
Removed dev-xenial from Chef
```

**Comment by majormoses** [comment]
@eheydrick so its just the webhook that is failing? if so if I can get some information on the webhook you are using to test I can try troubleshooting.

**Comment by eheydrick** [comment]
webhook and the sensu removal notification are failing. I have a webhook that looks like: 

```
:webhooks:
  ipa-node-deleter:
    :url: 'http://localhost:1234/node/{fqdn}'
    :method: DELETE
    :template_variables:
      :variable: 'fqdn'
      :method: 'get_chef_fqdn'
      :argument: '@instance_id'
    :chat:
      :enable: true
      :message: 'Removed {node} from FreeIPA'
      :variable: 'node'
      :method: 'get_chef_node_name'
      :argument: '@instance_id'
```

**Comment by majormoses** [comment]
@eheydrick I think you need to update the webhook config method  to include the module name? 
`:method: 'get_chef_fqdn'` to `AwsCleaner::Chef.get_chef_fqdn` or `Chef.get_chef_fqdn` I will try to take a closer look over the weekend.I don't see anything in your output to indicate an issue from sensu (other than its lack of being present) can you confirm that there is no output at all?

**Comment by majormoses** [comment]
@eheydrick did updating the webhook config work?

**Comment by majormoses** [comment]
@eheydrick did updating the webhook configs change anything?

**Comment by eheydrick** [comment]
Oh shoot, apologies this fell off my radar. Going to give it a shot tomorrow.

**Comment by majormoses** [comment]
I looked into the sensu issue and was able to reproduce the sensu issue I have tested it and its working now.

Chef and Sensu:
```
Looking at message number 0
Removed ip-10-55-141-195.us-west-2.compute.internal from Chef
Removed ip-10-55-141-195.us-west-2.compute.internal from Sensu
Got 0 messages
```

Hipchat:
image

**Comment by majormoses** [comment]
@eheydrick I validated the core functionality are good and have a seperate commit for you to test webhooks with so I can itterate over that. it would be nice if we could include a simple webhook in for testing. If its not working for you could you maybe commit to a branch your webhook or at least something that gives the basics of it so I can use that to test?

**Comment by eheydrick** [comment]
I got webhooks working again! I made some changes to your last commit and verified chef and sensu removal and webhooks are all working. Take a look at https://github.com/eheydrick/aws-cleaner/commit/bb93c7abcb139466e5f0a816fa3a7c4b3b144715. I reworked the webhook template stuff and got rid of the `eval` too. Probably could be further improved but it works without any changes to the config. You want to cherry-pick that in to your PR and I'll merge if you're ready?

To get a webhook for testing, take a look at the README for an example or here's a more fleshed out one from my config: 

```
:webhooks:
  ipa-node-deleter:
    :url: 'http://localhost:8989/node/{fqdn}'
    :method: DELETE
    :template_variables:
      :variable: 'fqdn'
      :method: 'get_chef_fqdn'
      :argument: '@instance_id'
    :chat:
      :enable: true
      :message: 'Removed {node} from FreeIPA'
      :variable: 'node'
      :method: 'get_chef_node_name'
      :argument: '@instance_id'
```

**Comment by majormoses** [comment]
@eheydrick added your patch and rebased.

**Comment by eheydrick** [comment]
Thanks again @majormoses!

**Pull request merged**
